# Adapted from Omarchy v3.8.4 (MIT)
# App-specific window rules
source = /usr/share/gentoozinho/default/hypr/apps/browser.conf
source = /usr/share/gentoozinho/default/hypr/apps/hyprshot.conf
source = /usr/share/gentoozinho/default/hypr/apps/system.conf
source = /usr/share/gentoozinho/default/hypr/apps/terminals.conf
source = /usr/share/gentoozinho/default/hypr/apps/walker.conf
