masters = gentoo
repo-name = gentoozinho
thin-manifests = true
sign-manifests = false
sign-commits = false
profile-formats = portage-2
cache-formats = md5-dict
manifest-hashes = BLAKE2B SHA512
manifest-required-hashes = BLAKE2B
