# Adapted from Omarchy v3.8.4 (MIT)
# Laptop multimedia keys for volume and LCD brightness (with OSD)
bindeld = ,XF86AudioRaiseVolume, Volume up, exec, gentoozinho-swayosd-client --output-volume raise
bindeld = ,XF86AudioLowerVolume, Volume down, exec, gentoozinho-swayosd-client --output-volume lower
bindeld = ,XF86AudioMute, Mute, exec, gentoozinho-swayosd-client --output-volume mute-toggle
bindeld = ,XF86MonBrightnessUp, Brightness up, exec, gentoozinho-brightness-display +5%
bindeld = ,XF86MonBrightnessDown, Brightness down, exec, gentoozinho-brightness-display 5%-
bindeld = SHIFT, XF86MonBrightnessUp, Brightness maximum, exec, gentoozinho-brightness-display 100%
bindeld = SHIFT, XF86MonBrightnessDown, Brightness minimum, exec, gentoozinho-brightness-display 1%

# Precise 1% multimedia adjustments with Alt modifier
bindeld = ALT, XF86AudioRaiseVolume, Volume up precise, exec, gentoozinho-swayosd-client --output-volume +1
bindeld = ALT, XF86AudioLowerVolume, Volume down precise, exec, gentoozinho-swayosd-client --output-volume -1
bindeld = ALT, XF86MonBrightnessUp, Brightness up precise, exec, gentoozinho-brightness-display +1%
bindeld = ALT, XF86MonBrightnessDown, Brightness down precise, exec, gentoozinho-brightness-display 1%-

# Requires playerctl
bindld = , XF86AudioNext, Next track, exec, gentoozinho-swayosd-client --playerctl next
bindld = , XF86AudioPause, Pause, exec, gentoozinho-swayosd-client --playerctl play-pause
bindld = , XF86AudioPlay, Play, exec, gentoozinho-swayosd-client --playerctl play-pause
bindld = , XF86AudioPrev, Previous track, exec, gentoozinho-swayosd-client --playerctl previous

